# Base image
FROM node:22

# starting point
WORKDIR /app

# copy package.json and package-lock.json to the working directory
COPY package*.json ./

# install app dependencies
RUN npm install

COPY . . 

# Set port enviorments
ENV PORT=3000
# Expose the port the app runs on
EXPOSE 3000

CMD ["npm", "start"]